# Generated by Django 4.0.4 on 2022-04-28 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_category_product_designation_product_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='code',
            field=models.CharField(default='product_', max_length=100),
        ),
    ]
